// Package all registers every command of the REQUIRED set via blank imports:
// the 116 POSIX-required names ∪ GNU coreutils that bashy implements as Go
// applets, plus the two certification applets (posix-gate, posix-providers).
// This is the certified inventory — the multicall binary cmd/coreutils links
// exactly this list and nothing from yoke.
//
// Everything else that used to live here (the agentic and non-POSIX applets:
// ast, browser, fetch, jq, tar, tree, which, …) moved to
// github.com/qiangli/yoke/cmds/all, which blank-imports this package and adds
// its own. Consumers that want the whole userland import yoke's list;
// consumers that want the certified set import this one.
//
// Membership is ONE rule, recorded row by row in the umbrella's
// docs/coreutils-required-set.tsv: a name stays iff it is POSIX-required or a
// GNU coreutils program (yoke's atlas.PosixRequired ∪ atlas.GNUCoreutilsUpstream).
//
// Keep the list alphabetical.
package all

import (
	_ "github.com/qiangli/coreutils/cmds/arch"
	_ "github.com/qiangli/coreutils/cmds/at"
	_ "github.com/qiangli/coreutils/cmds/awk"
	_ "github.com/qiangli/coreutils/cmds/b2sum"
	_ "github.com/qiangli/coreutils/cmds/base32"
	_ "github.com/qiangli/coreutils/cmds/base64"
	_ "github.com/qiangli/coreutils/cmds/basename"
	_ "github.com/qiangli/coreutils/cmds/basenc"
	_ "github.com/qiangli/coreutils/cmds/batch"
	_ "github.com/qiangli/coreutils/cmds/bc"
	_ "github.com/qiangli/coreutils/cmds/cat"
	_ "github.com/qiangli/coreutils/cmds/chcon"
	_ "github.com/qiangli/coreutils/cmds/chgrp"
	_ "github.com/qiangli/coreutils/cmds/chmod"
	_ "github.com/qiangli/coreutils/cmds/chown"
	_ "github.com/qiangli/coreutils/cmds/cksum"
	_ "github.com/qiangli/coreutils/cmds/cmp"
	_ "github.com/qiangli/coreutils/cmds/comm"
	_ "github.com/qiangli/coreutils/cmds/cp"
	_ "github.com/qiangli/coreutils/cmds/crontab"
	_ "github.com/qiangli/coreutils/cmds/csplit"
	_ "github.com/qiangli/coreutils/cmds/cut"
	_ "github.com/qiangli/coreutils/cmds/date"
	_ "github.com/qiangli/coreutils/cmds/dd"
	_ "github.com/qiangli/coreutils/cmds/df"
	_ "github.com/qiangli/coreutils/cmds/diff"
	_ "github.com/qiangli/coreutils/cmds/dir"
	_ "github.com/qiangli/coreutils/cmds/dircolors"
	_ "github.com/qiangli/coreutils/cmds/dirname"
	_ "github.com/qiangli/coreutils/cmds/du"
	_ "github.com/qiangli/coreutils/cmds/echo"
	_ "github.com/qiangli/coreutils/cmds/ed"
	_ "github.com/qiangli/coreutils/cmds/env"
	_ "github.com/qiangli/coreutils/cmds/expand"
	_ "github.com/qiangli/coreutils/cmds/expr"
	_ "github.com/qiangli/coreutils/cmds/factor"
	_ "github.com/qiangli/coreutils/cmds/false"
	_ "github.com/qiangli/coreutils/cmds/file"
	_ "github.com/qiangli/coreutils/cmds/find"
	_ "github.com/qiangli/coreutils/cmds/fmt"
	_ "github.com/qiangli/coreutils/cmds/fold"
	_ "github.com/qiangli/coreutils/cmds/getconf"
	_ "github.com/qiangli/coreutils/cmds/grep"
	_ "github.com/qiangli/coreutils/cmds/groups"
	_ "github.com/qiangli/coreutils/cmds/head"
	_ "github.com/qiangli/coreutils/cmds/hostid"
	_ "github.com/qiangli/coreutils/cmds/hostname"
	_ "github.com/qiangli/coreutils/cmds/iconv"
	_ "github.com/qiangli/coreutils/cmds/id"
	_ "github.com/qiangli/coreutils/cmds/install"
	_ "github.com/qiangli/coreutils/cmds/join"
	_ "github.com/qiangli/coreutils/cmds/kill"
	_ "github.com/qiangli/coreutils/cmds/link"
	_ "github.com/qiangli/coreutils/cmds/ln"
	_ "github.com/qiangli/coreutils/cmds/locale"
	_ "github.com/qiangli/coreutils/cmds/logger"
	_ "github.com/qiangli/coreutils/cmds/logname"
	_ "github.com/qiangli/coreutils/cmds/ls"
	_ "github.com/qiangli/coreutils/cmds/mailx"
	_ "github.com/qiangli/coreutils/cmds/make"
	_ "github.com/qiangli/coreutils/cmds/md5sum"
	_ "github.com/qiangli/coreutils/cmds/mesg"
	_ "github.com/qiangli/coreutils/cmds/mkdir"
	_ "github.com/qiangli/coreutils/cmds/mkfifo"
	_ "github.com/qiangli/coreutils/cmds/mknod"
	_ "github.com/qiangli/coreutils/cmds/mktemp"
	_ "github.com/qiangli/coreutils/cmds/more"
	_ "github.com/qiangli/coreutils/cmds/mv"
	_ "github.com/qiangli/coreutils/cmds/newgrp"
	_ "github.com/qiangli/coreutils/cmds/nice"
	_ "github.com/qiangli/coreutils/cmds/nl"
	_ "github.com/qiangli/coreutils/cmds/nohup"
	_ "github.com/qiangli/coreutils/cmds/nproc"
	_ "github.com/qiangli/coreutils/cmds/numfmt"
	_ "github.com/qiangli/coreutils/cmds/od"
	_ "github.com/qiangli/coreutils/cmds/paste"
	_ "github.com/qiangli/coreutils/cmds/patch"
	_ "github.com/qiangli/coreutils/cmds/pathchk"
	_ "github.com/qiangli/coreutils/cmds/pax"
	_ "github.com/qiangli/coreutils/cmds/pinky"
	_ "github.com/qiangli/coreutils/cmds/posixgate"
	_ "github.com/qiangli/coreutils/cmds/posixproviders"
	_ "github.com/qiangli/coreutils/cmds/pr"
	_ "github.com/qiangli/coreutils/cmds/printenv"
	_ "github.com/qiangli/coreutils/cmds/printf"
	_ "github.com/qiangli/coreutils/cmds/ps"
	_ "github.com/qiangli/coreutils/cmds/ptx"
	_ "github.com/qiangli/coreutils/cmds/pwd"
	_ "github.com/qiangli/coreutils/cmds/readlink"
	_ "github.com/qiangli/coreutils/cmds/realpath"
	_ "github.com/qiangli/coreutils/cmds/renice"
	_ "github.com/qiangli/coreutils/cmds/rm"
	_ "github.com/qiangli/coreutils/cmds/rmdir"
	_ "github.com/qiangli/coreutils/cmds/sed"
	_ "github.com/qiangli/coreutils/cmds/seq"
	_ "github.com/qiangli/coreutils/cmds/sha1sum"
	_ "github.com/qiangli/coreutils/cmds/sha224sum"
	_ "github.com/qiangli/coreutils/cmds/sha256sum"
	_ "github.com/qiangli/coreutils/cmds/sha384sum"
	_ "github.com/qiangli/coreutils/cmds/sha512sum"
	_ "github.com/qiangli/coreutils/cmds/shred"
	_ "github.com/qiangli/coreutils/cmds/shuf"
	_ "github.com/qiangli/coreutils/cmds/sleep"
	_ "github.com/qiangli/coreutils/cmds/sort"
	_ "github.com/qiangli/coreutils/cmds/split"
	_ "github.com/qiangli/coreutils/cmds/stat"
	_ "github.com/qiangli/coreutils/cmds/stdbuf"
	_ "github.com/qiangli/coreutils/cmds/strings"
	_ "github.com/qiangli/coreutils/cmds/stty"
	_ "github.com/qiangli/coreutils/cmds/sum"
	_ "github.com/qiangli/coreutils/cmds/sync"
	_ "github.com/qiangli/coreutils/cmds/tabs"
	_ "github.com/qiangli/coreutils/cmds/tac"
	_ "github.com/qiangli/coreutils/cmds/tail"
	_ "github.com/qiangli/coreutils/cmds/talk"
	_ "github.com/qiangli/coreutils/cmds/tee"
	_ "github.com/qiangli/coreutils/cmds/test"
	_ "github.com/qiangli/coreutils/cmds/time"
	_ "github.com/qiangli/coreutils/cmds/timeout"
	_ "github.com/qiangli/coreutils/cmds/touch"
	_ "github.com/qiangli/coreutils/cmds/tput"
	_ "github.com/qiangli/coreutils/cmds/tr"
	_ "github.com/qiangli/coreutils/cmds/true"
	_ "github.com/qiangli/coreutils/cmds/truncate"
	_ "github.com/qiangli/coreutils/cmds/tsort"
	_ "github.com/qiangli/coreutils/cmds/tty"
	_ "github.com/qiangli/coreutils/cmds/uname"
	_ "github.com/qiangli/coreutils/cmds/unexpand"
	_ "github.com/qiangli/coreutils/cmds/uniq"
	_ "github.com/qiangli/coreutils/cmds/unlink"
	_ "github.com/qiangli/coreutils/cmds/uptime"
	_ "github.com/qiangli/coreutils/cmds/users"
	_ "github.com/qiangli/coreutils/cmds/uudecode"
	_ "github.com/qiangli/coreutils/cmds/uuencode"
	_ "github.com/qiangli/coreutils/cmds/vdir"
	_ "github.com/qiangli/coreutils/cmds/wc"
	_ "github.com/qiangli/coreutils/cmds/who"
	_ "github.com/qiangli/coreutils/cmds/whoami"
	_ "github.com/qiangli/coreutils/cmds/write"
	_ "github.com/qiangli/coreutils/cmds/xargs"
	_ "github.com/qiangli/coreutils/cmds/yes"
)
