// Package all registers every implemented command via blank imports.
// Consumers that want the whole userland import this one package;
// consumers embedding a subset import the specific cmds packages.
//
// Keep the list alphabetical; it is the shipped-tool inventory
// (docs/commands.md is the plan, this is the build).
package all

import (
	_ "github.com/qiangli/coreutils/cmds/base32"
	_ "github.com/qiangli/coreutils/cmds/base64"
	_ "github.com/qiangli/coreutils/cmds/basename"
	_ "github.com/qiangli/coreutils/cmds/cat"
	_ "github.com/qiangli/coreutils/cmds/chgrp"
	_ "github.com/qiangli/coreutils/cmds/chmod"
	_ "github.com/qiangli/coreutils/cmds/chown"
	_ "github.com/qiangli/coreutils/cmds/cmp"
	_ "github.com/qiangli/coreutils/cmds/comm"
	_ "github.com/qiangli/coreutils/cmds/cp"
	_ "github.com/qiangli/coreutils/cmds/cut"
	_ "github.com/qiangli/coreutils/cmds/date"
	_ "github.com/qiangli/coreutils/cmds/df"
	_ "github.com/qiangli/coreutils/cmds/diff"
	_ "github.com/qiangli/coreutils/cmds/dirname"
	_ "github.com/qiangli/coreutils/cmds/du"
	_ "github.com/qiangli/coreutils/cmds/echo"
	_ "github.com/qiangli/coreutils/cmds/env"
	_ "github.com/qiangli/coreutils/cmds/false"
	_ "github.com/qiangli/coreutils/cmds/find"
	_ "github.com/qiangli/coreutils/cmds/grep"
	_ "github.com/qiangli/coreutils/cmds/gzip"
	_ "github.com/qiangli/coreutils/cmds/head"
	_ "github.com/qiangli/coreutils/cmds/hexdump"
	_ "github.com/qiangli/coreutils/cmds/hostname"
	_ "github.com/qiangli/coreutils/cmds/id"
	_ "github.com/qiangli/coreutils/cmds/join"
	_ "github.com/qiangli/coreutils/cmds/link"
	_ "github.com/qiangli/coreutils/cmds/ln"
	_ "github.com/qiangli/coreutils/cmds/ls"
	_ "github.com/qiangli/coreutils/cmds/md5sum"
	_ "github.com/qiangli/coreutils/cmds/mkdir"
	_ "github.com/qiangli/coreutils/cmds/mktemp"
	_ "github.com/qiangli/coreutils/cmds/mv"
	_ "github.com/qiangli/coreutils/cmds/paste"
	_ "github.com/qiangli/coreutils/cmds/printenv"
	_ "github.com/qiangli/coreutils/cmds/pwd"
	_ "github.com/qiangli/coreutils/cmds/readlink"
	_ "github.com/qiangli/coreutils/cmds/realpath"
	_ "github.com/qiangli/coreutils/cmds/rm"
	_ "github.com/qiangli/coreutils/cmds/rmdir"
	_ "github.com/qiangli/coreutils/cmds/seq"
	_ "github.com/qiangli/coreutils/cmds/sha1sum"
	_ "github.com/qiangli/coreutils/cmds/sha224sum"
	_ "github.com/qiangli/coreutils/cmds/sha256sum"
	_ "github.com/qiangli/coreutils/cmds/sha384sum"
	_ "github.com/qiangli/coreutils/cmds/sha512sum"
	_ "github.com/qiangli/coreutils/cmds/shuf"
	_ "github.com/qiangli/coreutils/cmds/sleep"
	_ "github.com/qiangli/coreutils/cmds/sort"
	_ "github.com/qiangli/coreutils/cmds/split"
	_ "github.com/qiangli/coreutils/cmds/stat"
	_ "github.com/qiangli/coreutils/cmds/strings"
	_ "github.com/qiangli/coreutils/cmds/sync"
	_ "github.com/qiangli/coreutils/cmds/tac"
	_ "github.com/qiangli/coreutils/cmds/tail"
	_ "github.com/qiangli/coreutils/cmds/tar"
	_ "github.com/qiangli/coreutils/cmds/tee"
	_ "github.com/qiangli/coreutils/cmds/touch"
	_ "github.com/qiangli/coreutils/cmds/tr"
	_ "github.com/qiangli/coreutils/cmds/true"
	_ "github.com/qiangli/coreutils/cmds/truncate"
	_ "github.com/qiangli/coreutils/cmds/tsort"
	_ "github.com/qiangli/coreutils/cmds/tty"
	_ "github.com/qiangli/coreutils/cmds/uname"
	_ "github.com/qiangli/coreutils/cmds/uniq"
	_ "github.com/qiangli/coreutils/cmds/unlink"
	_ "github.com/qiangli/coreutils/cmds/uptime"
	_ "github.com/qiangli/coreutils/cmds/wc"
	_ "github.com/qiangli/coreutils/cmds/which"
	_ "github.com/qiangli/coreutils/cmds/whoami"
	_ "github.com/qiangli/coreutils/cmds/yes"
)
