package sota

import (
	"regexp"
	"strings"
	"time"

	"github.com/qiangli/coreutils/pkg/kb"
	"github.com/qiangli/coreutils/pkg/scope"
)

// kbStore resolves the active kb store (repo docs/kb/ or host), or nil if none.
// A sota report is cached AS A KB PAGE — so it is reused, discoverable via
// `bashy search --kb`, and the same durable memory the fleet already shares.
func kbStore() *kb.Store {
	sc, err := scope.Resolve(scope.Options{
		RepoSub: kb.RepoSub,
		HostDir: func() (string, error) { return kb.DefaultDir(), nil },
	})
	if err != nil {
		return nil
	}
	return kb.Open(sc.Dir())
}

var slugRe = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(q string) string {
	s := slugRe.ReplaceAllString(strings.ToLower(q), "-")
	s = strings.Trim(s, "-")
	if len(s) > 60 {
		s = s[:60]
	}
	return "sota-" + s
}

// cachedFresh returns the cached page if it exists AND is within maxAge — the
// reuse gate (research once, many read; do not re-spend on a fresh question).
func cachedFresh(store *kb.Store, slug string, maxAge time.Duration) (*kb.Page, bool) {
	if store == nil {
		return nil, false
	}
	p, err := store.Load(slug)
	if err != nil || p == nil {
		return nil, false
	}
	ts := p.Updated
	if ts == "" {
		ts = p.Created
	}
	t, perr := time.Parse(time.RFC3339, ts)
	if perr != nil {
		return p, false
	}
	if maxAge > 0 && time.Since(t) > maxAge {
		return p, false // exists but stale
	}
	return p, true
}

// cacheReport writes (or updates) the sota page in kb.
func cacheReport(store *kb.Store, slug, question, report string) error {
	if store == nil {
		return nil
	}
	op, created := "add", ""
	if old, err := store.Load(slug); err == nil && old != nil {
		op, created = "update", old.Created
	}
	return store.Write(&kb.Page{
		Slug:        slug,
		Type:        "fact",
		Title:       "SOTA — " + question,
		Description: "Current state-of-the-art on " + question + " (auto-generated by bashy sota; cited + dated)",
		Tags:        []string{"sota", "research"},
		Created:     created,
		Body:        report,
	}, op)
}
