#!/usr/bin/env python3
"""Generate the shipped Bashy applet coverage/provider matrix."""

from __future__ import annotations

import argparse
import csv
import io
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# GNU all-known command inventory from docs/reference-coreutils-comparison.md,
# intersected with command names (the multicall entrypoint itself is omitted).
GNU = set("""
[ arch b2sum base32 base64 basename basenc cat chcon chgrp chmod chown chroot
cksum comm cp csplit cut date dd df dir dircolors dirname du echo env expand expr
factor false fmt fold groups head hostid hostname id install join kill link ln
logname ls md5sum mkdir mkfifo mknod mktemp mv nice nl nohup nproc numfmt od
paste pathchk pinky pr printenv printf ptx pwd readlink realpath rm rmdir runcon
seq sha1sum sha224sum sha256sum sha384sum sha512sum shred shuf sleep sort split
stat stdbuf stty sum sync tac tail tee test timeout touch tr true truncate tsort
tty uname unexpand uniq unlink uptime users vdir wc who whoami yes
""".split())

# Exact name intersection measured from the configured VSC-PCTS2016 POSIX08
# runscen and the staged 2026-08-05 Bashy multicall inventory.
VSC_NAMED = set("""
at awk basename batch cat chgrp chmod chown cksum cmp comm cp crontab csplit cut
date dd df diff dirname du echo env expand expr false find fold grep head id join
kill ln logname ls mkdir mkfifo more mv nice nohup od paste pathchk pr printf pwd
rm rmdir sed sleep sort split strings stty tail tee test time touch tr true tsort
tty uname unexpand uniq wc who xargs
""".split())

ALIASES = {
    "[": "test",
    "gunzip": "gzip",
    "ncal": "cal",
    "sntp": "ntp",
    "zcat": "gzip",
}

TEST_FUNC = re.compile(r"^func (?:Test|Fuzz|Benchmark)\w+", re.MULTILINE)
IMPORT = re.compile(r'github\.com/qiangli/coreutils/cmds/([^"/]+)"')


def shipped_packages() -> list[str]:
    text = (ROOT / "cmds/all/all.go").read_text()
    return sorted(set(IMPORT.findall(text)))


def package_tests(package: str) -> tuple[int, int]:
    files = sorted((ROOT / "cmds" / package).glob("*_test.go"))
    funcs = sum(len(TEST_FUNC.findall(path.read_text())) for path in files)
    return len(files), funcs


def rows() -> list[dict[str, str | int]]:
    packages = shipped_packages()
    applet_package = {package: package for package in packages}
    for applet, package in ALIASES.items():
        if package not in applet_package:
            raise SystemExit(f"alias {applet!r} refers to unshipped package {package!r}")
        applet_package[applet] = package

    result: list[dict[str, str | int]] = []
    for applet in sorted(applet_package):
        package = applet_package[applet]
        files, funcs = package_tests(package)
        if applet in GNU:
            family = "GNU Coreutils"
        elif applet in VSC_NAMED:
            family = "POSIX/Unix utility"
        else:
            family = "Bashy/other extension"
        result.append({
            "applet": applet,
            "go_package": f"cmds/{package}",
            "alias_of": package if applet in ALIASES else "",
            "family": family,
            "gnu_coreutils": "yes" if applet in GNU else "no",
            "vsc_named_tset": "yes" if applet in VSC_NAMED else "no",
            "test_files": files,
            "test_functions": funcs,
        })

    if len(packages) != 136 or len(result) != 141:
        raise SystemExit(
            f"inventory changed: packages={len(packages)} applets={len(result)}; "
            "update the documented snapshot and generator assertions"
        )
    if any(row["test_files"] == 0 for row in result):
        missing = [str(row["applet"]) for row in result if row["test_files"] == 0]
        raise SystemExit("shipped applets lack package-local tests: " + ", ".join(missing))
    return result


def render_tsv(data: list[dict[str, str | int]]) -> str:
    fields = list(data[0])
    handle = io.StringIO(newline="")
    writer = csv.DictWriter(handle, fieldnames=fields, delimiter="\t", lineterminator="\n")
    writer.writeheader()
    writer.writerows(data)
    return handle.getvalue()


def render_markdown(data: list[dict[str, str | int]]) -> str:
    gnu = sum(row["gnu_coreutils"] == "yes" for row in data)
    vsc = sum(row["vsc_named_tset"] == "yes" for row in data)
    aliases = sum(bool(row["alias_of"]) for row in data)
    lines = [
        "# Bashy shipped applet matrix",
        "",
        "Generated by `scripts/applet-matrix.py`; do not hand-edit the table.",
        "Snapshot: 2026-08-05, after withholding `chroot` and `runcon` pending",
        "privileged integration coverage.",
        "",
        "## Interpretation",
        "",
        "- **GNU Coreutils** means the name belongs to GNU Coreutils' all-known",
        "  command inventory. It does not claim complete GNU option parity.",
        "- **VSC named tset** means the configured VSC-PCTS2016 POSIX08 Commands",
        "  & Utilities scenario contains a test set with the same name. It does",
        "  not prove that every applet option is covered or that an applet with",
        "  `no` is never invoked indirectly.",
        "- **Test files/functions** count package-local Go test files and top-level",
        "  `Test`, `Fuzz`, and `Benchmark` functions. Table-driven subtests are not",
        "  expanded, so these are structural indicators rather than coverage percentages.",
        "- Aliases share their implementation package but are listed separately",
        "  because they are separately advertised command names.",
        "",
        "## Totals",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Shipped Go command packages | 136 |",
        f"| Advertised applet names | {len(data)} |",
        f"| Alias applet names | {aliases} |",
        f"| GNU Coreutils names | {gnu} |",
        f"| Names with a configured VSC test set | {vsc} |",
        f"| Names without a configured VSC test set | {len(data) - vsc} |",
        "| Shipped names lacking package-local tests | 0 |",
        "| Release-withheld implementations | 2 (`chroot`, `runcon`) |",
        "",
        "The machine-readable source is `docs/applet-matrix.tsv`.",
        "",
        "## Complete matrix",
        "",
        "| Applet | Go package | Alias of | Family | GNU | VSC named tset | Test files | Test functions |",
        "|---|---|---|---|:---:|:---:|---:|---:|",
    ]
    for row in data:
        alias = str(row["alias_of"]) or "—"
        applet = f"`{row['applet']}`"
        lines.append(
            f"| {applet} | `{row['go_package']}` | {alias} | {row['family']} | "
            f"{row['gnu_coreutils']} | {row['vsc_named_tset']} | "
            f"{row['test_files']} | {row['test_functions']} |"
        )
    lines.extend([
        "",
        "## Release-withheld implementations",
        "",
        "| Name | Reason not advertised | Return condition |",
        "|---|---|---|",
        "| `chroot` | privileged root/credential behavior lacks bounded integration coverage | prove root change, credentials, child status, and cleanup |",
        "| `runcon` | SELinux label transition has only superficial coverage | prove transition, child status, restoration, and unsupported platforms |",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    data = rows()
    tsv = ROOT / "docs/applet-matrix.tsv"
    markdown = ROOT / "docs/applet-matrix.md"
    rendered_tsv = render_tsv(data)
    rendered_markdown = render_markdown(data)
    if args.check:
        if not tsv.exists() or not markdown.exists() or tsv.read_text() != rendered_tsv or markdown.read_text() != rendered_markdown:
            raise SystemExit("applet matrix was stale; regenerate with scripts/applet-matrix.py")
        print("applet-matrix: PASS")
        return
    tsv.write_text(rendered_tsv)
    markdown.write_text(rendered_markdown)
    print(f"applet-matrix: wrote {len(data)} applets")


if __name__ == "__main__":
    main()
